common/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = "common"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'common/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'common/logout.html'), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from post.views import PostList

urlpatterns = [
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path("", PostList.as_view(), name='index'),
]

post/urls.py
from django.urls import path
from .views import PostList, PostDelete, PostDetail, PostUpdate, PostCreate, PostLike, PostFavorite, PostLikeList,\
    PostFavoriteList, PostMyList
from django.conf.urls.static import static
from django.conf import settings


app_name = "post"
urlpatterns = [
    path("create/", PostCreate.as_view(), name='create'),
    path("like/<int:post_id>/", PostLike.as_view(), name='like'),
    path('favorite/<int:post_id>/', PostFavorite.as_view(), name='favorite'),
    path("delete/<int:pk>", PostDelete.as_view(), name='delete'),
    path("update/<int:pk>", PostUpdate.as_view(), name='update'),
    path("detail/<int:pk>", PostDetail.as_view(), name='detail'),
    path("like/", PostLikeList.as_view(), name='like_list'),
    path("favorite/", PostFavoriteList.as_view(), name='favorite_list'),
    path("mylist/", PostMyList.as_view(), name='mylist'),
    path("", PostList.as_view(), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def __str__(self):
        return "text : "+ self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('post:detail', args=[self.id])

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields =('username', 'email')

common/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate, login

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1) #로그인
            login(request, user)   # 세션 권한을 획득(인증)
            return redirect('index')
    else:  # GET
        form = UserForm()
    context = {'form': form}
    return render(request, 'common/signup.html', context)

post/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Post
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse


class PostMyList(ListView):
    model = Post
    template_name = 'post/post_mylist.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       #로그인확인
            messages.warning(request, '로그인이 필요한기능입니다.')
            return HttpResponseRedirect('/')
        return super(PostMyList, self).dispatch(request, *args, **kwargs)



class PostLikeList(ListView):
    model = Post
    template_name = 'post/post_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       #로그인확인
            messages.warning(request, '로그인이 필요한기능입니다.')
            return HttpResponseRedirect('/')
        return super(PostLikeList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 좋아요한글 보여주기
        user = self.request.user
        queryset = user.like_post.all()
        return queryset


class PostFavoriteList(ListView):
    model = Post
    template_name = 'post/post_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       #로그인확인
            messages.warning(request, '로그인이 필요한기능입니다.')
            return HttpResponseRedirect('/')
        return super(PostFavoriteList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 저장한글 보여주기
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset


class PostLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       # 로그인확인
            return HttpResponseForbidden()
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.like.all():
                    post.like.remove(user)
                else:
                    post.like.add(user)

            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PostFavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       # 로그인확인
            return HttpResponseForbidden()
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.favorite.all():
                    post.favorite.remove(user)
                else:
                    post.favorite.add(user)
            return HttpResponseRedirect('/')


class PostList(ListView):
    model = Post
    template_name_suffix = '_list'


class PostCreate(CreateView):
    model = Post
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 정상작동 한다면
            # form : 모델폼
            form.instance.save()
            return redirect('/')
        else:
            # 정상작동 X
            return self.render_to_response({'form': form})


class PostUpdate(UpdateView):
    model = Post
    fields = ['text', 'image']
    template_name_suffix = '_update'
    # success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)


class PostDelete(DeleteView):
    model = Post
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정 권한이 없습니다.')
            return HttpResponseRedirect('/')
            # 삭제 페이지에서 권한이 없다 출력
            # detail페이지로 되돌아가서 삭제실패 출력
        else:
            return super(PostDelete, self).dispatch(request, *args, **kwargs)


class PostDetail(DetailView):
    model = Post
    template_name_suffix = '_detail'

post/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teamstagram</title>
    <link rel="stylesheet" type= "text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type= "text/css" href="{% static 'css/common.css' %}">
    <style>
    .container2 {
    width: 350px;
    height: 350px;
    margin: 100px auto;
    display: flex;
    flex-direction: column;
    align-content: center;
    flex-wrap: wrap;
    background-color: #fff;
    border: 1px solid #DBDBDB;
}
.container3 {
    width: 350px;
    height: 450px;
    margin: 100px auto;
    display: flex;
    flex-direction: column;
    align-content: center;
    flex-wrap: wrap;
    background-color: #fff;
    border: 1px solid #DBDBDB;
}
img.logo_instagram {
    align-self: center;
    width: 175px;
    margin: 30px 45px
}
.input_login {
    width: 270px;
    height: 40px;
    margin: 3px auto;
    padding: 0 10px;
    display: block;
    background-color: #fafafa;
    border: 1px solid #DBDBDB;
    border-radius: 3px;
    font-size: 14px;
}
.input_login::placeholder {
    font-size: 12px;
    color: #8e8e8e;
}
.input_login:focus {
    border: 1px solid #8a8a8a;
    outline: none;
}
.btn_login {
    width: 268px;
    height: 30px;
    margin: 13px auto;
    background-color: #0095f6;
    border: none;
    border-radius: 3px;
    color: white;
    font-size: 14px;
    font-weight: 600;
}
.btn_login:disabled {
    background-color: #B9DFFC;
}
.btn_login:disabled:hover {
    cursor: default;
}
.btn_login:enabled:hover {
    cursor: pointer;
}
.btn_login:focus {
    outline: none;
}
a {
    cursor: default;
}
    </style>
</head>
<body>
  <div class="container2">
  <div>
    <div>
      <img class="logo_instagram" src="{% static 'images/team_stagram.png' %}" alt="instagram_logo">
    </div>
  </div>
  <form action="{% url 'common:login' %}" method="post" class="post-form">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">사용자ID</label>
      <input type="text" class="input_login" name="username" id="username" placeholder="전화번호, 사용자 이름 또는 이메일"
             aria-label="Input ID" value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" class="input_login" name="password" id="password" placeholder="비밀번호"
             aria-label="Input password" value="{{ form.password.value|default_if_none:'' }}">
    </div>
    <button type="submit" class="btn_login my-3">로그인</button>
    <div>
          <h6>계정이 없으신가요?<a href="{% url 'common:signup' %}">가입하기</a></h6>
    </div>
      </form>
  </div>
</body>
{% endblock %}

post/templates/common/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃이 잘 되었습니다. </div>
        <a href="{% url 'accounts:login'%}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

post/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
    <link rel="stylesheet" type= "text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type= "text/css" href="{% static 'css/common.css' %}">
    <style>
        .container2 {
    width: 350px;
    height: 350px;
    margin: 100px auto;
    display: flex;
    flex-direction: column;
    align-content: center;
    flex-wrap: wrap;
    background-color: #fff;
    border: 1px solid #DBDBDB;
}
.container3 {
    width: 350px;
    height: 450px;
    margin: 100px auto;
    display: flex;
    flex-direction: column;
    align-content: center;
    flex-wrap: wrap;
    background-color: #fff;
    border: 1px solid #DBDBDB;
}
img.logo_instagram {
    align-self: center;
    width: 175px;
    margin: 30px 45px
}
.input_login {
    width: 270px;
    height: 40px;
    margin: 3px auto;
    padding: 0 10px;
    display: block;
    background-color: #fafafa;
    border: 1px solid #DBDBDB;
    border-radius: 3px;
    font-size: 14px;
}
.input_login::placeholder {
    font-size: 12px;
    color: #8e8e8e;
}
.input_login:focus {
    border: 1px solid #8a8a8a;
    outline: none;
}
.btn_login {
    width: 268px;
    height: 30px;
    margin: 13px auto;
    background-color: #0095f6;
    border: none;
    border-radius: 3px;
    color: white;
    font-size: 14px;
    font-weight: 600;
}
.btn_login:disabled {
    background-color: #B9DFFC;
}
.btn_login:disabled:hover {
    cursor: default;
}
.btn_login:enabled:hover {
    cursor: pointer;
}
.btn_login:focus {
    outline: none;
}
a {
    cursor: default;
}

    </style>
</head>
<body>
<div class="container3">
      <div>
      <img class="logo_instagram" src="{% static 'images/team_stagram.png' %}" alt="instagram_logo">
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" name="username" id="username" class="input_login" placeholder="전화번호, 사용자 이름 또는 이메일"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" name="password1" id="password1" class="input_login" placeholder="비밀번호"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" name="password2" id="password2" class="input_login" placeholder="비밀번호"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" name="email" id="email" class="input_login" placeholder="E-mail"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn_login">생성하기</button>
         <div>
           <h6>계정이 있으신가요?<a href="{% url 'common:login' %}">로그인</a></h6>
        </div>
    </form>
</div>
</body>
{% endblock %}

post/templates/form_errors.html
{% if form.errors %}  <!--필드 오류 출력 -->
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          <strong>{{ field.label }}</strong>
          {{error}}   <!-- 필수 항목입니다.-->
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류-->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

post/templates/post/post_create.html
{% extends 'base.html' %}
{% block content %}
<style>
    *{display: center;}
    #new-posting{text-align: center; font-weight: bold;font-size: 1.2em; margin: 20px 0px;}
    .btn-upload{
    color: yellowgreen; background-color: white; border: 1px solid yellowgreen;
    border-radius: 5px; float: right; margin-top: 10px;
    }
    .content{margin: 20px 0px;}
    p{font-size: 1em;}
    #id_text{width: 100%;}
    .container1{border-top: 1px solid #dedede; padding: 10px 0px;}
</style>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-8">
        <div class="posting-title">
            <p id="new-posting">새 게시물</p>
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            <input type="submit" value="Upload ✔" class="btn-upload">
            <div class="container1">
                <label for="id_image">이미지 업로드</label>
                <p class="content">
                    <input type="file" name="image" accept="image/*" id="id_image" >
                </p>
            </div>
            <!--    이미지 미리보기 영역   -->
            <div class="img_wrap">
                <img src="" id="preview" style="width: 500px; height: 500px;" alt="이미지추가"/>
            </div>
            <div class="container1">
                <p class="content">
                    <textarea name="text" id="text_field" cols="50" rows="5" placeholder="140자 까지 등록 가능합니다."></textarea>

                </p>
            </div>
            <!--            <div class="container1">-->
            <!--                <p>사람 태그하기</p>-->
            <!--            </div>-->
            <!--            <div class="container1">-->
            <!--                <p>위치 추가</p>-->
            <!--            </div>-->
        </form>
    </div>
    <div class="col"></div>
</div>
{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">

$('#id_image').change(function(){
    setImageFromFile(this, '#preview');
});

function setImageFromFile(input, expression) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $(expression).attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
{% endblock %}
{% endblock %}

post/templates/post/post_delete.html
{% extends 'base.html' %}
{% block content %}
<!--진짜 지울건지 확인을 받아야 한다. form을 또 보여줄 필요가 없다.-->
<div class="alert alert-primary" role="alert">
  정말로 {{object}}를 삭제 하시겠습니까?
</div>
<form action="" method ="post">
    {% csrf_token%}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

post/templates/post/post_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="margin-top: 100px;">
            <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ object.author }}</h5>
                <p class="card-text"> {{ object.text }} </p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'post:like' object.id %}"
                               class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요</a>
                        {% if object.like.all.count %}
                        <span class="float-left">
                                {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'post:favorite' object.id %}"
                               class="float-right btn-favorite {% if user in object.favorite.all %}active{% endif %}">저장하기</a>
                    </li>

                    <li class="list-group-item">생성일 : {{object.created}}</li>
                    <li class="list-group-item">
                        <!-- disqus 활용한 댓글 구현    -->
                        {% load disqus_tags %}
                        <div class="card-body">
                             {% disqus_show_comments %}
                        </div>
                    </li>
                </ul>
            </div>
            <div class="card-body">
                <a href="{% url 'post:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'post:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

post/templates/post/post_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5">

            {% for object in object_list %}

            <article class="card mb-4" style="margin-top: 50px;">
                <div class="card-header">
                    {{ object.author }}
                </div>

                <img src="{{ object.image.url }}" class="card-img-top" alt="...">
                <p class="card-text" style="margin-top:20px; margin-left:5px;"> {{ object.text }} </p>
                <div class="card-text">
                    <ul class="list-group list-group-flush">

                        <li class="list-group-item">
                            <a href="{% url 'post:like' object.id %}"
                               class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요</a>
                            {% if object.like.all.count %}
                            <span class="float-left">
                                {{object.like.all.count}}
                            </span>
                            {% endif %}
                            <a href="{% url 'post:favorite' object.id %}"
                               class="float-right btn-favorite {% if user in object.favorite.all %}active{% endif %}">저장하기</a>
                        </li>
                    </ul>
                        <li class="list-group-item">생성일 : {{object.created}}</li>

                </div>
                <div class="card-body">
                    <a href="{% url 'post:detail' object.id %} " class="card-link">댓글달기</a>
                    {% if user == object.author %}
                    <a href="{% url 'post:update' object.id %} " class="card-link">수정하기</a>
                    <a href="{% url 'post:delete' object.id %} " class="card-link">삭제하기</a>
                    {% endif %}
                </div>
            </article>
            {% endfor %}
        </div>

        <div class="col">
            {% load static %}
            <div class="card" style="margin-top: 50px;">
               <img src="{{user.profile_src_img}}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{user}}</h5>
                    <p class="card-text">회원님의 스토리를 확인하세요</p>
                    <a href="{% url 'post:mylist' %}" class="btn btn-primary">회원님의 스토리 이동</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

post/templates/post/post_mylist.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<!--profile-->
<div class="container">
    <section class="row">
        <header class="card-header" style="display:flex;">
            <div class="profile_warp" style="margin-top:50px">
                {% load static %}
                <button type="button" id="btn-upload" style="border:0; box-sizing: border-box;">
                    <img src="{% static 'images/IMG_10.jpg' %}" id="profile_img" style="border:0; width:152px; height:152px; border-radius:50%;" alt="...">
                </button>
                <div>
                    <form id="signform" name="signform" method="POST" ENCTYPE="multipart/form-data" action=" ">
                        {% csrf_token %}
                        <input type="file" id="file" name="file" style="display:none;" onchange="changeValue(this)">
                        <input type="hidden" name = "target_url">
                    </form>
                </div>
            </div>
            <section class="profile_detail" style="display:flex; flex-direction:column;">
                <div class="top" style=" display: flex; align-items: center;">
                    <h2 class="user_name" style="font-size:28px; font-weight:300; font-height:32px; display:inline-block; margin-top:50px; padding: 3px 20px;:">
                        {{user}}</h2>
                </div>
                <div class="profile_modify" style="width:397px; box-sizing:border-box; display:block; border:1px solid #ccc; justify-content: center;
                     text-align:center; ">
                    <a href="#" class="profile_edit" style="text-decoration:none; ">프로필편집</a>
                </div>
            </section>
        </header>
        <div class="middle" style="border:0;">
            <div class="profile">
                <p class="user_name">이름</p>
                <p class="card-text">{{user.profile_msg}}</p>
            </div>
            <div class="card" style="margin-bottom:20px;">
                <p class="card-text" style="text-align:center;">게시물</p>
            </div>
        </div>
        <!-- Gallery -->
        <div class="row">
          <div class="col-md-12">
              <div class="row">
                  {% for object in object_list %}
                  {% if object.author == request.user %}
                  <figure class="col-md-4">
                      <img src="{{object.image.url}}" class="w-100 shadow-1-strong rounded mb-4" alt="">
                  </figure>
                  {% endif %}
                  {% endfor %}
              </div>
          </div>
        </div>
    </section>
</div>
<!-- Gallery -->
{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    // 이미지 클릭시 업로드창 실행
    $('#btn-upload').click(function(e){
        e.preventDefault();
        $('#file').click();
    });
    // 이미지 변경
    $("input[name='file']").change(function(e){
        $( "#profile_img" ).submit();
        $("input[name='file']").val();
        var frm = document.getElementById('btn-upload');
        frm.method = 'POST';
        frm.enctype = 'multipart/form-data';
        var fileData = new FormData(frm)
    });
});
</script>

{% endblock %}

{% endblock %}

post/templates/post/post_update.html
{% extends 'base.html' %}
{% block content %}
<style>
    *{display: center;}
    #new-posting{text-align: center; font-weight: bold;font-size: 1.2em; margin: 20px 0px;}
    .btn-upload{
    color: yellowgreen; background-color: white; border: 1px solid yellowgreen;
    border-radius: 5px; float: right; margin-top: 10px;
    }
    .content{margin: 20px 0px;}
    p{font-size: 1em;}
    #id_text{width: 100%;}
    .container1{border-top: 1px solid #dedede; padding: 10px 0px;}
    .load-image{margin-bottom: 20px;}
</style>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-8">
        <div class="posting-title">
            <p id="new-posting">게시물 수정</p>
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
<!--            취소버튼추가-->
            <div class="container1">
                <label>이미지 업로드</label>
            <input type="submit" value="Modify ✔" class="btn-upload">
            </div>
            <div class="img_wrap">
                <img src="" id="preview" style="width: 500px; height: 500px;" alt="이미지변경"/>
            </div>
            <div class="load-image">
                {{form.image}}
            </div>
            <div class="container1">
                {{form.text}}
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>


{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">

$('#id_image').change(function(){
    setImageFromFile(this, '#preview');
});

function setImageFromFile(input, expression) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $(expression).attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
{% endblock %}
{% endblock %}